################################################################
####################  -- DiscordBridge -- ######################
################################################################

# Put your discord bots token here.
token: "TOKEN HERE"

bridge-channel-id: 000000000000000